### ISSUE TITLE
QIIME2 Library page points to an outdated version

### ISSUE THREAD

**Issue by ElDeveloper** [biocore/evident#17]
Just noticed this while browsing the QIIME2 library. Seems like the README page points to @gibsramen's fork and to an older version of the document.

**Comment by gibsramen** [comment]
Good catch. I honestly forgot I had put Evident on Q2 library.

**Comment by gibsramen** [comment]
https://library.qiime2.org/plugins/evident/40/

Updated! Is there a way to automatically update these details when a new release is cut?

**Comment by ElDeveloper** [comment]
Very cool, thanks so much. I don't think there's a way but @ebolyen might now.

**Comment by ebolyen** [comment]
Not at the moment. There's a shiny future where these details would get pulled from the repositories outright, but nothing like that exists yet.
