### ISSUE TITLE
add "summarize_mdfdr.py" functionality to evident 

### ISSUE THREAD

**Issue by antgonza** [biocore/evident#5]
we need to add the summarizing into our code + testing

**Comment by serenejiang** [comment]
do we want to keep this as a separate python file or become part of the current effect size calculation code?

**Comment by serenejiang** [comment]
what is pp[8] in line 32? pp as the names of pickle file has only 7 elements for alpha effect size calculation? (I checked the filename in your original _generate_alphas() function, which is                     fname = join(output, '%s.%s.%s.%s.%s.pickle' % (alpha_method, afp, ac, mfp, col))). So the filename would look like "mannwhitneyu.alpha_pd.txt.Faith_PD.mapping_gender.txt.Gender.pickle". A similar question exists for beta diversity as well. Did I misunderstand something?

**Comment by antgonza** [comment]
1. separate python file?: yes
2. pp[8]?: it was the "merging" format for numeric categories; for AGP quartiles or deciles. Not relevant now. 

BTW, note that we should solve https://github.com/biocore/evident/issues/4 first before addressing this issue.
